# Generated by Django 5.0.4 on 2025-04-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_profil_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='user',
        ),
        migrations.AddField(
            model_name='profil',
            name='ish',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
